version: '3'
services:
  api-server:
     
      image: node-image-prod
      build: ./
      ports:
        - "5000:5000"
      env_file:
          - .env  
      command: npm run build


    
        